
server:
  port: 8082

spring:
  application:
    name: chatting-service
  datasource:
    url: jdbc:mysql://localhost:3306/animalwarChatting?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}